name: Update README With Wakatime Stats

on:
    workflow_dispatch:
    schedule:
      - cron: "0 */6 * * *"
    push:
        branches: [main]

jobs:
    update-readme:
        name: UPDATE README
        runs-on: ubuntu-latest
        steps:
          - uses: athul/waka-readme@master
            with:
                WAKATIME_API_KEY: ${{secrets.WAKATIME_API_KEY}}
                SHOW_TIME: true
                SHOW_TITLE: true
                SHOW_MASKED_TIME: true
                LANG_COUNT: 7
                TIME_RANGE: all_time
                STOP_AT_OTHER: false
                BLOCKS: ✦
                CODE_LANG: c++
                IGNORED_LANGUAGES: Binary YAML TOML JSON CMake Text
                COMMIT_MESSAGE: Updated README with new metrics
                COMMITTER_NAME: alexyzha
                COMMITTER_EMAIL: alexyzha@gmail.com
